<?php
/**
 * Global Breadcrumb.
 *
 * Renders the breadcrumb navigation generated by
 * conferp_get_breadcrumb_items().
 *
 * @package conferp
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}


/*
 * Breadcrumb items are passed through get_template_part().
 */
$items = isset( $args['items'] ) && is_array( $args['items'] )
	? $args['items']
	: array();


if ( empty( $items ) ) {
	return;
}
?>

<nav
	class="conferp-breadcrumb"
	aria-label="<?php esc_attr_e( 'Navegação estrutural', 'conferp' ); ?>"
>
	<ol class="conferp-breadcrumb__list">

		<?php foreach ( $items as $item ) : ?>

			<?php
			$label = isset( $item['label'] )
				? $item['label']
				: '';

			$url = isset( $item['url'] )
				? $item['url']
				: '';

			$current = ! empty( $item['current'] );


			if ( '' === $label ) {
				continue;
			}
			?>

			<li
				class="
					conferp-breadcrumb__item
					<?php echo $current ? 'is-current' : ''; ?>
				"
				<?php if ( $current ) : ?>
					aria-current="page"
				<?php endif; ?>
			>

				<?php if ( ! $current && ! empty( $url ) ) : ?>

					<a
						class="conferp-breadcrumb__link"
						href="<?php echo esc_url( $url ); ?>"
					>
						<?php echo esc_html( $label ); ?>
					</a>

				<?php else : ?>

					<span class="conferp-breadcrumb__current">
						<?php echo esc_html( $label ); ?>
					</span>

				<?php endif; ?>

			</li>

		<?php endforeach; ?>

	</ol>
</nav>