<?php
/**
 * Theme helper functions.
 *
 * @package conferp
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}


/**
 * Output an inline SVG icon from the theme icon library.
 *
 * SVG files are stored in:
 * /assets/img/icons/
 *
 * @param string $icon Icon identifier without .svg.
 * @param array  $args Optional SVG attributes.
 *
 * @return void
 */
function conferp_icon( $icon, $args = array() ) {

	/**
	 * Available theme icons.
	 */
	$icons = array(
		'accessibility'    => 'accessibility.svg',
		'back-to-top'      => 'back-to-top.svg',
		'chat'             => 'chat.svg',
		'contrast'         => 'menu.svg',
		'email'            => 'utility-symbol.svg',
		'facebook'         => 'facebook.svg',
		'instagram'        => 'instagram.svg',
		'linkedin'         => 'linkedin.svg',
		'registered-area'  => 'registered-area.svg',
		'search'           => 'search.svg',
		'transparency'     => 'transparency.svg',
		'universal-access' => 'universal-access.svg',
		'vlibras'          => 'vlibras.svg',
		'youtube'          => 'youtube.svg',
	);


	/**
	 * Prevent arbitrary file loading.
	 */
	if ( ! isset( $icons[ $icon ] ) ) {
		return;
	}


	$defaults = array(
		'class'       => '',
		'aria-hidden' => 'true',
		'focusable'   => 'false',
	);

	$args = wp_parse_args(
		$args,
		$defaults
	);


	$svg_path = get_template_directory()
		. '/assets/img/icons/'
		. $icons[ $icon ];


	if ( ! file_exists( $svg_path ) ) {
		return;
	}


	$svg = file_get_contents( $svg_path );

	if ( false === $svg ) {
		return;
	}


	// ======================================================
	// SVG cleanup
	// ======================================================


	/**
	 * Remove XML declaration.
	 */
	$svg = preg_replace(
		'/<\?xml.*?\?>/i',
		'',
		$svg
	);


	/**
	 * Remove DOCTYPE.
	 */
	$svg = preg_replace(
		'/<!DOCTYPE.*?>/i',
		'',
		$svg
	);


	/**
	 * Remove namespace declarations generated by
	 * some SVG normalization/export tools.
	 *
	 * Example:
	 *
	 * xmlns:ns0="http://www.w3.org/2000/svg"
	 */
	$svg = preg_replace(
		'/\s+xmlns:[a-zA-Z0-9_-]+="[^"]*"/',
		'',
		$svg
	);


	/**
	 * Remove namespace prefixes from SVG elements.
	 *
	 * Example:
	 *
	 * <ns0:path>
	 *
	 * becomes:
	 *
	 * <path>
	 */
	$svg = preg_replace(
		'/<(\/?)[a-zA-Z0-9_-]+:/',
		'<$1',
		$svg
	);


	// ======================================================
	// SVG attributes
	// ======================================================

	$attributes = '';


	if ( ! empty( $args['class'] ) ) {

		$attributes .= sprintf(
			' class="%s"',
			esc_attr( $args['class'] )
		);
	}


	$attributes .= sprintf(
		' aria-hidden="%s"',
		esc_attr( $args['aria-hidden'] )
	);


	$attributes .= sprintf(
		' focusable="%s"',
		esc_attr( $args['focusable'] )
	);


	/**
	 * Inject attributes into opening SVG.
	 */
	$svg = preg_replace(
		'/<svg\b/',
		'<svg' . $attributes,
		$svg,
		1
	);


	// ======================================================
	// Allowed SVG markup
	// ======================================================

	$allowed_svg = array(

		'svg' => array(
			'class'       => true,
			'xmlns'       => true,
			'viewbox'     => true,
			'width'       => true,
			'height'      => true,
			'fill'        => true,
			'stroke'      => true,
			'role'        => true,
			'aria-hidden' => true,
			'focusable'   => true,
		),

		'g' => array(
			'fill'         => true,
			'stroke'       => true,
			'stroke-width' => true,
			'transform'    => true,
			'clip-path'    => true,
			'mask'         => true,
			'opacity'      => true,
		),

		'path' => array(
			'd'               => true,
			'fill'            => true,
			'stroke'          => true,
			'stroke-width'    => true,
			'stroke-linecap'  => true,
			'stroke-linejoin' => true,
			'fill-rule'       => true,
			'clip-rule'       => true,
			'transform'       => true,
			'opacity'         => true,
		),

		'circle' => array(
			'cx'           => true,
			'cy'           => true,
			'r'            => true,
			'fill'         => true,
			'stroke'       => true,
			'stroke-width' => true,
		),

		'ellipse' => array(
			'cx'     => true,
			'cy'     => true,
			'rx'     => true,
			'ry'     => true,
			'fill'   => true,
			'stroke' => true,
		),

		'rect' => array(
			'x'            => true,
			'y'            => true,
			'width'        => true,
			'height'       => true,
			'rx'           => true,
			'ry'           => true,
			'fill'         => true,
			'stroke'       => true,
			'stroke-width' => true,
		),

		'line' => array(
			'x1'           => true,
			'y1'           => true,
			'x2'           => true,
			'y2'           => true,
			'stroke'       => true,
			'stroke-width' => true,
		),

		'polyline' => array(
			'points' => true,
			'fill'   => true,
			'stroke' => true,
		),

		'polygon' => array(
			'points' => true,
			'fill'   => true,
			'stroke' => true,
		),

		'defs' => array(),

		'clippath' => array(
			'id' => true,
		),

		'mask' => array(
			'id' => true,
		),

		'title' => array(),
	);


	echo wp_kses(
		$svg,
		$allowed_svg
	);
}